"""Initial schema

Revision ID: 21eab428e71f
Revises: 
Create Date: 2026-03-23 15:51:07.077405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21eab428e71f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('apify_api_token_encrypted', sa.Text(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('leads_raw',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('signal_category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_raw_company'), 'leads_raw', ['company'], unique=False)
    op.create_index(op.f('ix_leads_raw_email'), 'leads_raw', ['email'], unique=False)
    op.create_index(op.f('ix_leads_raw_processed'), 'leads_raw', ['processed'], unique=False)
    op.create_index(op.f('ix_leads_raw_signal_category'), 'leads_raw', ['signal_category'], unique=False)
    op.create_index(op.f('ix_leads_raw_user_id'), 'leads_raw', ['user_id'], unique=False)
    op.create_table('tracked_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_job_titles', sa.JSON(), nullable=True),
    sa.Column('target_locations', sa.JSON(), nullable=True),
    sa.Column('target_industries', sa.JSON(), nullable=True),
    sa.Column('company_sizes', sa.JSON(), nullable=True),
    sa.Column('excluded_keywords', sa.JSON(), nullable=True),
    sa.Column('lead_matching_mode', sa.Integer(), nullable=True),
    sa.Column('linkedin_page_url', sa.Text(), nullable=True),
    sa.Column('linkedin_profile_url', sa.Text(), nullable=True),
    sa.Column('track_profile_visitors', sa.Boolean(), nullable=True),
    sa.Column('company_followers_url', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('influencer_urls', sa.JSON(), nullable=True),
    sa.Column('track_top_profiles', sa.Boolean(), nullable=True),
    sa.Column('track_funding_events', sa.Boolean(), nullable=True),
    sa.Column('track_job_changes', sa.Boolean(), nullable=True),
    sa.Column('competitor_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_signals_status'), 'tracked_signals', ['status'], unique=False)
    op.create_index(op.f('ix_tracked_signals_user_id'), 'tracked_signals', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('outreach_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('generation_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_raw.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_drafts_lead_id'), 'outreach_drafts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outreach_drafts_status'), 'outreach_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_drafts_user_id'), 'outreach_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_drafts_user_id'), table_name='outreach_drafts')
    op.drop_index(op.f('ix_outreach_drafts_status'), table_name='outreach_drafts')
    op.drop_index(op.f('ix_outreach_drafts_lead_id'), table_name='outreach_drafts')
    op.drop_table('outreach_drafts')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_tracked_signals_user_id'), table_name='tracked_signals')
    op.drop_index(op.f('ix_tracked_signals_status'), table_name='tracked_signals')
    op.drop_table('tracked_signals')
    op.drop_index(op.f('ix_leads_raw_user_id'), table_name='leads_raw')
    op.drop_index(op.f('ix_leads_raw_signal_category'), table_name='leads_raw')
    op.drop_index(op.f('ix_leads_raw_processed'), table_name='leads_raw')
    op.drop_index(op.f('ix_leads_raw_email'), table_name='leads_raw')
    op.drop_index(op.f('ix_leads_raw_company'), table_name='leads_raw')
    op.drop_table('leads_raw')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
