"""add_user_settings_json

Revision ID: a24cd6cfaa7c
Revises: 21eab428e71f
Create Date: 2026-03-23 17:17:05.604053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24cd6cfaa7c'
down_revision: Union[str, Sequence[str], None] = '21eab428e71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_settings_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_settings_json')
    # ### end Alembic commands ###
