import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Sparkles, TrendingUp, AlertTriangle, Zap, ChevronRight, Loader2, RefreshCw } from "lucide-react";
import { toast } from "sonner";

const ICON_MAP = {
  insight: <TrendingUp className="w-4 h-4 text-blue-500" />,
  warning: <AlertTriangle className="w-4 h-4 text-yellow-500" />,
  opportunity: <Sparkles className="w-4 h-4 text-purple-500" />,
  action: <Zap className="w-4 h-4 text-orange-500" />,
};

const BG_MAP = {
  insight: "border-blue-100 bg-blue-50/50",
  warning: "border-yellow-100 bg-yellow-50/50",
  opportunity: "border-purple-100 bg-purple-50/50",
  action: "border-orange-100 bg-orange-50/50",
};

export default function InsightsPanel({ orgId }) {
  const [insights, setInsights] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [insightDate, setInsightDate] = useState(null);

  useEffect(() => {
    loadInsights();
  }, []);

  const loadInsights = async () => {
    setLoading(true);
    try {
      const today = new Date().toISOString().split("T")[0];
      const all = await base44.entities.DailyInsight.list("-created_date", 10);
      // Find today's insight or the most recent one
      const todayInsight = all.find(i => i.date === today) || all[0];
      if (todayInsight) {
        setInsights(todayInsight.insights || []);
        setInsightDate(todayInsight.date);
      }
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  };

  const generateNow = async () => {
    setGenerating(true);
    try {
      await base44.functions.invoke("generateDailyInsights", {});
      await loadInsights();
      toast.success("Insights generated by Monara");
    } catch (e) {
      toast.error("Failed to generate insights");
    }
    setGenerating(false);
  };

  return (
    <div className="bg-white rounded-xl border p-5">
      <div className="flex items-center justify-between mb-4">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-purple-500" />
            <h3 className="font-semibold text-gray-900">Monara's Daily Insights</h3>
          </div>
          <p className="text-xs text-gray-400">
            {insightDate
              ? `Generated for ${new Date(insightDate + "T12:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" })}`
              : "AI-powered proactive intelligence"}
          </p>
        </div>
        <button
          onClick={generateNow}
          disabled={generating}
          className="flex items-center gap-1.5 text-xs text-purple-600 font-medium hover:text-purple-800 disabled:opacity-50"
          title="Generate fresh insights now"
        >
          {generating ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
          {generating ? "Analyzing..." : "Refresh"}
        </button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-6">
          <Loader2 className="w-5 h-5 animate-spin text-purple-400" />
        </div>
      ) : insights.length === 0 ? (
        <div className="text-center py-6">
          <Sparkles className="w-8 h-8 text-gray-300 mx-auto mb-2" />
          <p className="text-sm text-gray-400">No insights yet.</p>
          <button
            onClick={generateNow}
            disabled={generating}
            className="mt-2 text-xs text-purple-600 font-medium hover:underline disabled:opacity-50"
          >
            {generating ? "Generating..." : "Generate now →"}
          </button>
        </div>
      ) : (
        <div className="space-y-3">
          {insights.map((ins, i) => (
            <div key={i} className={`rounded-lg border p-3 ${BG_MAP[ins.type] || "border-gray-100 bg-gray-50"}`}>
              <div className="flex items-start gap-2">
                <div className="flex-shrink-0 mt-0.5">{ICON_MAP[ins.type] || ICON_MAP.insight}</div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-sm font-semibold text-gray-900 truncate">{ins.title}</span>
                    {ins.metric && (
                      <span className="text-xs font-bold text-gray-500 flex-shrink-0">{ins.metric}</span>
                    )}
                  </div>
                  <p className="text-xs text-gray-600 mt-0.5 leading-relaxed">{ins.body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}